# Generated by Django 4.0 on 2022-02-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='librarian',
            field=models.BooleanField(default=False),
        ),
    ]
