# Generated by Django 4.0 on 2022-03-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_librarian'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hostel',
            field=models.CharField(choices=[('SR', 'Srinivas Ramanujan'), ('Gn', 'Gandhi'), ('Kr', 'Krishna'), ('Mr', 'Meera')], default='unknown', max_length=5),
        ),
        migrations.AddField(
            model_name='profile',
            name='room_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='mobile_num',
            field=models.CharField(max_length=15, verbose_name='Mobile/Contact number'),
        ),
    ]
