# Generated by Django 4.0 on 2022-03-08 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='merit_score',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
