# Generated by Django 4.0 on 2022-03-13 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_profile_merit_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='BITSID',
            new_name='bits_id',
        ),
    ]
