# Generated by Django 4.0 on 2022-03-13 20:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_bitsid_profile_bits_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_num',
            field=models.PositiveIntegerField(max_length=15, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(10)], verbose_name='Mobile/Contact number'),
        ),
    ]
