# Generated by Django 4.0 on 2022-03-16 07:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_bits_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='mobile_num',
            field=models.IntegerField(max_length=15, validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(1000000000)], verbose_name='Mobile/Contact number'),
        ),
    ]
