# Generated by Django 4.0 on 2022-01-17 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='none', max_length=100)),
                ('author', models.CharField(default='none', max_length=50)),
                ('publisher', models.CharField(default='none', max_length=50)),
                ('summary', models.CharField(default='none', max_length=500)),
                ('ISBN', models.IntegerField()),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
