# Generated by Django 4.0 on 2022-03-17 21:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('all_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('isbn', models.IntegerField(verbose_name='ISBN')),
                ('publisher', models.CharField(max_length=50)),
                ('location', models.CharField(default='unknown', max_length=20)),
                ('displayed_from', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('published', models.DateField(default=datetime.date(2022, 3, 18))),
                ('summary', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('issued', 'Issued'), ('returned', 'Returned'), ('rejected', 'Rejected'), ('renewed', 'Renewed')], default='pending', max_length=10, null=True)),
                ('reject_request', models.CharField(blank=True, max_length=300, null=True)),
                ('return_on', models.DateTimeField(default=datetime.datetime(2022, 4, 7, 3, 15, 56, 892697), null=True)),
                ('issued_on', models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 18, 3, 15, 56, 892697), null=True)),
                ('requested_on', models.DateTimeField(default=datetime.datetime(2022, 3, 18, 3, 15, 56, 892697), null=True)),
                ('returned_on', models.DateTimeField(default=datetime.datetime(2022, 3, 18, 3, 15, 56, 892697), null=True)),
                ('renewed_on', models.DateTimeField(default=datetime.datetime(2022, 3, 18, 3, 15, 56, 892697), null=True)),
                ('rating', models.IntegerField(blank=True, choices=[(0, 'No Rating'), (1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=0, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('score', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='all_books.book')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Books',
        ),
        migrations.AddField(
            model_name='book',
            name='availability',
            field=models.ManyToManyField(through='all_books.Issue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='all_books.Genre'),
        ),
    ]
