# Generated by Django 4.0 on 2022-03-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0002_issue2_remove_books_isbn_books_displayed_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue2',
            name='reject_request',
            field=models.CharField(default='none', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='issue2',
            name='issue_request_status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
