# Generated by Django 4.0 on 2022-03-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0003_issue2_reject_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue2',
            name='reject_request',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
