# Generated by Django 4.0 on 2022-03-03 12:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0004_alter_issue2_reject_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue2',
            name='return_on',
            field=models.DateTimeField(default=datetime.date.today, null=True),
        ),
    ]
