# Generated by Django 4.0 on 2022-03-03 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0005_alter_issue2_return_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue2',
            name='return_on',
            field=models.DateTimeField(default=datetime.date(2022, 3, 23), null=True),
        ),
    ]
