# Generated by Django 4.0 on 2022-03-05 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0006_alter_issue2_return_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue2',
            name='issue_request_status',
            field=models.CharField(choices=[(True, 'issued'), (False, 'returned')], default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='issue2',
            name='return_on',
            field=models.DateTimeField(default=datetime.date(2022, 3, 26), null=True),
        ),
    ]
