# Generated by Django 4.0 on 2022-03-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0007_alter_issue2_issue_request_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue2',
            name='issue_request_status',
            field=models.CharField(choices=[(True, 'keep issued'), (False, 'return')], default=False, max_length=10),
        ),
    ]
