# Generated by Django 4.0 on 2022-03-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0008_alter_issue2_issue_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue2',
            name='issue_request_status',
            field=models.CharField(choices=[('1', 'keep issued'), ('foo', 'return')], default=False, max_length=10),
        ),
    ]
