# Generated by Django 4.0 on 2022-03-05 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0011_alter_issue2_issue_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue2',
            name='reject_request',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
