# Generated by Django 4.0 on 2022-03-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0012_alter_issue2_reject_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue2',
            name='issue_request_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('issued', 'Issued'), ('returned', 'Returned')], default='pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='issue2',
            name='reject_request',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
