# Generated by Django 4.0 on 2022-03-05 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0013_alter_issue2_issue_request_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue2',
            name='reject_request',
            field=models.CharField(default='', max_length=300, null=True),
        ),
    ]
