# Generated by Django 4.0 on 2022-03-05 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0015_alter_issue2_reject_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue2',
            name='reject_request',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
