# Generated by Django 4.0 on 2022-03-06 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0017_alter_issue2_issue_request_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue2',
            name='return_on',
            field=models.DateField(default=datetime.date(2022, 3, 26), null=True),
        ),
    ]
