# Generated by Django 4.0 on 2022-03-07 06:25

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('all_books', '0018_alter_issue2_return_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
        migrations.AlterField(
            model_name='issue2',
            name='return_on',
            field=models.DateField(default=datetime.date(2022, 3, 27), null=True),
        ),
    ]
