# Generated by Django 4.0 on 2022-03-07 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('all_books', '0019_rename_books_book_alter_issue2_return_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Issue2',
            new_name='Issue',
        ),
    ]
