# Generated by Django 4.0 on 2022-03-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0020_rename_issue2_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='un-classified', max_length=20),
        ),
        migrations.AddField(
            model_name='book',
            name='location',
            field=models.CharField(default='unknown', max_length=20),
        ),
    ]
