# Generated by Django 4.0 on 2022-03-07 08:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0021_book_genre_book_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='displayed_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 7, 13, 30, 57, 223538), null=True),
        ),
    ]
