# Generated by Django 4.0 on 2022-03-07 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0027_alter_book_displayed_from_alter_issue_issued_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='displayed_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 7, 18, 1, 1, 429908), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issued_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 7, 18, 1, 1, 429908), null=True),
        ),
    ]
