# Generated by Django 4.0 on 2022-03-07 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0028_alter_book_displayed_from_alter_book_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='displayed_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 7, 18, 4, 32, 173562), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issued_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 7, 18, 4, 32, 173562), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
