# Generated by Django 4.0 on 2022-03-07 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0032_alter_book_displayed_from_alter_issue_issued_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='displayed_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 7, 23, 14, 2, 673542), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issued_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 7, 23, 14, 2, 673542), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(0, 'No Rating'), (1, 'Poor'), (2, 'Average'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=0, null=True),
        ),
    ]
