# Generated by Django 4.0 on 2022-03-07 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0033_alter_book_displayed_from_alter_issue_issued_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='renewed_on',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='returned_on',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='displayed_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 8, 3, 13, 42, 364485), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issued_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 8, 3, 13, 42, 364485), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='return_on',
            field=models.DateField(default=datetime.date(2022, 3, 28), null=True),
        ),
    ]
