# Generated by Django 4.0 on 2022-03-07 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0034_issue_renewed_on_issue_returned_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='displayed_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 8, 4, 5, 6, 571958), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issue_request_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('issued', 'Issued'), ('returned', 'Returned'), ('rejected', 'Rejected'), ('renewed', 'Renewed')], default='pending', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issued_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 8, 4, 5, 6, 571958), null=True),
        ),
    ]
