# Generated by Django 4.0 on 2022-03-14 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0058_alter_book_displayed_from_alter_book_isbn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='displayed_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 14, 12, 59, 40, 484192), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issued_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 14, 12, 59, 40, 484192), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='renewed_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 12, 59, 40, 484192), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='requested_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 12, 59, 40, 484192), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='return_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 12, 59, 40, 484192), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='returned_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 12, 59, 40, 484192), null=True),
        ),
    ]
