# Generated by Django 4.0 on 2022-03-14 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0060_genre_alter_book_displayed_from_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genre',
            field=models.CharField(default='jj', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='displayed_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 14, 14, 46, 4, 40970), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issued_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 14, 14, 46, 4, 40970), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='renewed_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 14, 46, 4, 40970), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='requested_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 14, 46, 4, 40970), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='return_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 3, 14, 46, 4, 40970), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='returned_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 14, 14, 46, 4, 40970), null=True),
        ),
    ]
