# Generated by Django 4.0 on 2022-03-14 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0062_rename_genre_genre_name_alter_book_displayed_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='issue_request_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='book',
            name='displayed_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 15, 0, 42, 48, 84786), null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(default=datetime.date(2022, 3, 15)),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issued_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 15, 0, 42, 48, 84786), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='renewed_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 0, 42, 48, 84786), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='requested_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 0, 42, 48, 84786), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='return_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 4, 0, 42, 48, 84786), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='returned_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 15, 0, 42, 48, 84786), null=True),
        ),
    ]
