# Generated by Django 4.0 on 2022-03-16 08:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('all_books', '0068_alter_book_displayed_from_alter_issue_issued_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='displayed_from',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 16, 8, 54, 32, 897, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='issued_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 3, 16, 14, 24, 32, 897), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='renewed_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 14, 24, 32, 897), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='requested_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 14, 24, 32, 897), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='return_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 5, 14, 24, 32, 897), null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='returned_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 16, 14, 24, 32, 897), null=True),
        ),
    ]
